name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
# on: [push, pull_request]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Build
        run: |
          uv sync --locked --all-extras --dev
          uv build
          uvx rstcheck README.rst
      - uses: actions/upload-artifact@v4
        with:
          path: dist/

  upload_pypi:
    needs: [build_sdist]
    runs-on: ubuntu-latest
    permissions:
      contents: read  # to download the artifact
      packages: write  # to upload to PyPI
      id-token: write  # needed for pypi action
      # Note: 'contents: read' is sufficient for downloading artifacts, but 'contents: write' is needed for uploading packages.
    # upload to PyPI on every tag starting with 'v'
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
